name: 'Xcode Package to ZIP and DMG'
description: 'Package an .app into a .zip and .dmg without codesigning or notarization'
branding:
  icon: 'package'
  color: 'green'

inputs:
  build-name:
    description: 'Path of the software to package. Globbing is supported'
    required: true

  xcode-path:
    description: 'Path of the Xcode version to use'
    required: true
    default: '/Applications/Xcode_13.2.1.app'

runs:
  using: 'composite'
  steps:
    - name: Setup Xcode
      run: sudo xcode-select -s ${{ inputs.xcode-path }}
      shell: bash

    - name: Create ${{ inputs.build-name }}.dmg
      run: |
        brew install create-dmg
        mkdir -p ./bin/dmg-workspace
        ditto "./bin/${{ inputs.build-name }}.app" "./bin/dmg-workspace/${{ inputs.build-name }}.app"
        create-dmg \
          --volname "Install ${{ inputs.build-name }}" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "${{ inputs.build-name }}.app" 200 190 \
          --hide-extension "${{ inputs.build-name }}.app" \
          --app-drop-link 600 185 \
          "./bin/${{ inputs.build-name }}.dmg" \
          "./bin/dmg-workspace"
      shell: bash

    - name: Create ${{ inputs.build-name }}.app.zip
      run: ditto -c -k --keepParent "./bin/${{inputs.build-name}}.app" "./bin/${{inputs.build-name}}.app.zip"
      shell: bash
