// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as grpcmd$0 from "./internal/grpcmd/models.js";

export function CallWithResult(address: string, method: string, metadata: string, req: string, protoPaths: string[], protoFiles: string[]): $CancellablePromise<grpcmd$0.Result> {
    return $Call.ByID(913647537, address, method, metadata, req, protoPaths, protoFiles).then(($result: any) => {
        return $$createType0($result);
    });
}

export function MethodTemplate(address: string, method: string): $CancellablePromise<string> {
    return $Call.ByID(3477185463, address, method);
}

export function NonambiguousMethods(address: string): $CancellablePromise<string[]> {
    return $Call.ByID(2002104549, address).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = grpcmd$0.Result.createFrom;
const $$createType1 = $Create.Array($Create.Any);
